name: DartLearning
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sealed_class: 3.0.0
  json_serializable: ^3.3.0
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  sealed_class_generator: 3.0.0
  build_runner: ^1.8.0
  test: ^1.6.0
